name: Deploy Docs

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: init git user
        run: |
          git config user.name action
          git config user.email action@github.com

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: using pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.x

      - name: install dependencies
        run: pnpm i

      - name: build docs
        run: |
          npm run docs:build
          cp -r docs/dist ../pages

      - name: deploy
        run: |
          git clean -ffdx
          git fetch
          git checkout gh-pages
          cp -r ../pages/* .
          git add .
          git commit -m "update docs"
          git push
