name: Deploy Docs

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: using pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 6.x
      
      - name: install dependencies
        run: pnpm i

      - name: build docs
        run: |
          npm run docs:build
          cp -r docs/dist ../pages
        
      - name: deploy
        run: |
          git clean -ffdx
          git checkout gh-pages
          cp -r ../pages/ pwd
          git config user.name action
          git config user.email action@github.com
          git add .
          git commit -m "update docs"
          git push
  

        
