name: update pnpm lock file

on:
  pull_request:
    branches: ["master"]
    types: ["opened"]

permissions: write-all

jobs:
  deployment:
    runs-on: ubuntu-latest
    env:
      HEAD_REF: ${{ github.event.pull_request.head.ref }}

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: using pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.x

      - name: Condition Step
        if: ${{ github.actor == 'dependabot[bot]' }}
        run: |
          echo labels contains dependencies

      - name: update dependencies
        if: ${{ github.actor == 'dependabot[bot]' }}
        run: |
          pnpm i --no-frozen-lockfile
          git config user.name action
          git config user.email action@github.com
          git add pnpm-lock.yaml
          git commit -m "build: update pnpm lock file"
          git push origin HEAD:$HEAD_REF
