name: Deploy Preview Docs

on:
  pull_request:
    branches: ["master"]
    types: ["opened", "synchronize", "closed"]

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment:
      name: gh-pages
      url: ${{ steps.deploy_environment.outputs.url }}
    env:
      PR_TITLE: ${{ github.event.pull_request.title }}
      PR_NUMBER: ${{ github.event.number }}
      PR_TYPE: ${{ github.event.action }}

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: using pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 6.x

      - name: init git user
        run: |
          git config user.name action
          git config user.email action@github.com

      - name: install dependencies
        if: ${{ env.PR_TYPE != 'closed' }}
        run: pnpm i
        env:
          NPM_TOKEN: ${{ secrets.NPMJS_PUBLISH_TOKEN }}

      - name: build docs
        if: ${{ env.PR_TYPE != 'closed' }}
        run: |
          npm run docs:build
          cp -r docs/dist ../pages
        env:
          NPM_TOKEN: ${{ secrets.NPMJS_PUBLISH_TOKEN }}

      - name: deploy
        if: ${{ env.PR_TYPE != 'closed' }}
        run: |
          git clean -ffdx
          git checkout gh-pages
          git pull
          subdir=${PR_TITLE////_}
          subdir=${subdir// /_}
          echo "Deploying PR: $PR_TITLE to pr/$subdir"
          mkdir -p pr/$subdir
          cp -r ../pages/* pr/$subdir
          ls
          git add .
          git commit -m "update docs from pr #$PR_NUMBER"
          git push

      - name: "comment on pr"
        id: deploy_environment
        if: ${{ env.PR_TYPE != 'closed' }}
        run: |
          subdir=${PR_TITLE////_}
          subdir=${subdir// /_}
          gh api \
            -H "Accept: application/vnd.github+json" \
            /repos/MarvelSQ/experiment/pages >> pages.json
          url=$(grep -o '"html_url":"[^"]*' pages.json | grep -o '[^"]*$')
          echo "::set-output name=url::${url}pr/$subdir"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: clean
        if: ${{ env.PR_TYPE == 'closed' }}
        run: |
          git clean -ffdx
          git checkout gh-pages
          git pull
          subdir=${PR_TITLE////_}
          subdir=${subdir// /_}
          rm -rf pr/$subdir
          git add .
          git commit -m "clean docs from pr #$PR_NUMBER"
          git push
