name: prelease

on:
  push:
    branches: [ "alpha", "beta" , "next" ]
  pull_request:
    branches: [ "alpha", "beta" , "next" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v3
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: using pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 6.x

      - name: install dependencies
        run: pnpm i
        
      - name: publish
        run: |
          npm run build
          npm version prerelease --preid=${{ GITHUB_REF_NAME }} && npm publish --tag=${{ GITHUB_REF_NAME }}
        
      - name: sync build
        run: |
          git push
