name: Test

on:
  push:
    branches: ["master"]
  pull_request:
    types: ["opened", "synchronize"]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: using pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.x

      - name: install dependencies
        run: pnpm i
        env:
          NPM_TOKEN: ${{ secrets.NPMJS_PUBLISH_TOKEN }}

      - name: run test script
        run: npm test
        env:
          NPM_TOKEN: ${{ secrets.NPMJS_PUBLISH_TOKEN }}
